global:
  name: vtask
  namespace: media
image:
  repository: harbor.rwiv.xyz/private/vtask
  tag: 0.0.0
  pullSecret: image-pull-secret
affinity: {}
podLabels:
  sidecar.istio.io/inject: "true"
redis:
  host: vtask-redis-master.media.svc.cluster.local
  port: 6379
  secretName: vtask-redis
  passwordKey: password
server:
  replicas: 1
  service:
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 30280
flower:
  replicas: 1
  unauthenticatedApi: true
  service:
    type: NodePort
    port: 80
    targetPort: 5555
    nodePort: 30281
