global:
  name: vodify
  namespace: media
image:
  repository: harbor.rwiv.xyz/private/vodify
  tag: 0.0.0
  pullSecret: image-pull-secret
affinity: ~
podLabels: ~
redis:
  host: vodify-redis-master.media.svc.cluster.local
  port: 6379
  secretName: vodify-redis
  passwordKey: password
secrets:
  sqs:
    secretName: sqs-auth
    accessKeyKey: access-key
    secretKeyKey: secret-key
  recnodeQueue:
    secretName: recnode-queue
    regionNameKey: region-name
    queueUrlKey: queue-url
server:
  replicas: 1
  service:
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 30280
flower:
  replicas: 1
  unauthenticatedApi: true
  service:
    type: NodePort
    port: 80
    targetPort: 5555
    nodePort: 30281
