apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vodify
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rwiv/gitops-prod.git
    targetRevision: HEAD
    path: apps/media/vodify-server
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: true
