services:
  vidt-archive:
    image: harbor.rwiv.xyz/private/vidt:0.8.8
    container_name: vidt-archive
    working_dir: /app
    entrypoint: .venv/bin/python3 -m vidt batch
    environment:
      PY_ENV: prod
      BATCH_COMMAND: archive

      ARCHIVE_CONFIG_PATH: /mnt/app/archive_conf.yaml

      UNTF_ENDPOINT: "${UNTF_ENDPOINT}"
      UNTF_API_KEY: "${UNTF_API_KEY}"
      UNTF_TOPIC: "${UNTF_TOPIC}"
    volumes:
      - "${ARCHIVE_OUT_DIR_PATH}:/mnt/volume/out"
      - "${ARCHIVE_TMP_DIR_PATH}:/mnt/volume/tmp"
      - "${ARCHIVE_CONFIG_PATH}:/mnt/app/archive_conf.yaml"
    labels:
      app: vidt
      host: ${HOSTNAME}
    logging:
      driver: json-file
      options:
        labels: app,host
        tag: "container_image={{.ImageName}},container_name={{.Name}}"
