services:
  vtask-video:
    image: harbor.rwiv.xyz/private/vtask:0.1.8
    container_name: vtask-video
    working_dir: /app
    entrypoint: python -m vtask batch
    environment:
      PY_ENV: prod
      BATCH_COMMAND: video
      TMP_DIR_PATH: /app/tmp

      VIDEO_DOWNLOAD_CONFIG_PATH: /mnt/app/video_conf.yaml

      UNTF_ENDPOINT: "${UNTF_ENDPOINT}"
      UNTF_API_KEY: "${UNTF_API_KEY}"
      UNTF_TOPIC: "${UNTF_TOPIC}"
    volumes:
      - "${SRC_DIR_PATH}/video:/mnt/volume"
      - "${VIDEO_DOWNLOAD_CONFIG_PATH}:/mnt/app/video_conf.yaml"
