services:
  vidt-batch:
    image: harbor.rwiv.xyz/private/vidt:0.9.2
    container_name: vidt-batch
    working_dir: /app
    entrypoint: .venv/bin/python3 -m vidt batch
    environment:
      PY_ENV: prod
      ARCHIVE_CONFIG_PATH: /mnt/app/conf.yaml
      UNTF_ENDPOINT: "${UNTF_ENDPOINT}"
      UNTF_API_KEY: "${UNTF_API_KEY}"
      UNTF_TOPIC: "${UNTF_TOPIC}"
    volumes:
      - "${BASE_DIR_PATH}:/mnt/volume"
      - "${CONFIG_PATH}:/mnt/app/conf.yaml"
    labels:
      app: vidt
      host: ${HOSTNAME}
    logging:
      driver: json-file
      options:
        labels: app,host
        tag: "container_image={{.ImageName}},container_name={{.Name}}"
