services:
  vtask-worker-local:
    image: ghcr.io/rwiv/vtask:0.3.2
    container_name: vtask-worker-local
    working_dir: /app
    entrypoint: python -m vtask worker
    restart: always
    environment:
      PY_ENV: prod
      WORKER_NAME: local
      TMP_DIR_PATH: "/app/tmp"

      OUT_FS_NAME: "${OUT_FS_NAME}"
      FS_CONFIG_PATH: "/mnt/app_conf/fs_conf.yaml"
      STDL_BASE_DIR_PATH: "/mnt/stdl/src"
      STDL_IS_ARCHIVE: "${STDL_IS_ARCHIVE}"
      NETWORK_IO_DELAY_MS: "${NETWORK_IO_DELAY_MS}"
      NETWORK_BUF_SIZE: "${NETWORK_BUF_SIZE}"

      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      CELERY_WORKER_CONCURRENCY: "${CELERY_LOCAL_WORKER_CONCURRENCY}"
      CELERY_VISIBILITY_TIMEOUT_SEC: "${CELERY_VISIBILITY_TIMEOUT_SEC}"
    volumes:
      - "${TMP_DIR_PATH}:/app/tmp"
      - "${STDL_BASE_DIR_PATH}:/mnt/stdl/src"
      - "${FS_CONFIG_PATH}:/mnt/app_conf/fs_conf.yaml"
  vtask-worker-remote:
    image: ghcr.io/rwiv/vtask:0.3.2
    container_name: vtask-worker-remote
    working_dir: /app
    entrypoint: python -m vtask worker
    restart: always
    environment:
      PY_ENV: prod
      WORKER_NAME: remote
      TMP_DIR_PATH: "/app/tmp"

      OUT_FS_NAME: "${OUT_FS_NAME}"
      FS_CONFIG_PATH: "/mnt/app_conf/fs_conf.yaml"
      STDL_BASE_DIR_PATH: "/mnt/stdl/src"
      STDL_IS_ARCHIVE: "${STDL_IS_ARCHIVE}"
      NETWORK_IO_DELAY_MS: "${NETWORK_IO_DELAY_MS}"
      NETWORK_BUF_SIZE: "${NETWORK_BUF_SIZE}"

      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      CELERY_WORKER_CONCURRENCY: "${CELERY_REMOTE_WORKER_CONCURRENCY}"
      CELERY_VISIBILITY_TIMEOUT_SEC: "${CELERY_VISIBILITY_TIMEOUT_SEC}"
    volumes:
      - "${TMP_DIR_PATH}:/app/tmp"
      - "${STDL_BASE_DIR_PATH}:/mnt/stdl/src"
      - "${FS_CONFIG_PATH}:/mnt/app_conf/fs_conf.yaml"
