services:
  vidt-batch:
#    image: vidt-gpu:latest
    image: vidt-enc:latest
    container_name: vidt-batch
    working_dir: /app
#    entrypoint: python3 -m vidt batch
    entrypoint: .venv/bin/python3 -m vidt batch
    environment:
      PY_ENV: prod
      UNTF_ENDPOINT: "${UNTF_ENDPOINT}"
      UNTF_API_KEY: "${UNTF_API_KEY}"
      UNTF_TOPIC: "${UNTF_TOPIC}"
    volumes:
      - "${BASE_DIR_PATH}:/mnt/volume/app"
      - "${ARCHIVE_CONFIG_PATH}:/mnt/app/archive_conf.yaml"
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [gpu,video]
