services:
  vtask-enc:
    image: vtask-gpu:latest
    container_name: vtask-enc
    working_dir: /app
    entrypoint: python -m vtask batch
    environment:
      PY_ENV: prod
      BATCH_COMMAND: encoding

      ENCODING_CONFIG_PATH: /mnt/app/encoding_conf.yaml

      UNTF_ENDPOINT: "${UNTF_ENDPOINT}"
      UNTF_API_KEY: "${UNTF_API_KEY}"
      UNTF_TOPIC: "${UNTF_TOPIC}"
    volumes:
      - "${ENCODING_BASE_DIR_PATH}:/mnt/volume/app"
      - "${ENCODING_CONFIG_PATH}:/mnt/app/encoding_conf.yaml"
    labels:
      app: vtask
      host: ${HOSTNAME}
    logging:
      driver: json-file
      options:
        labels: app,host
        tag: "container_image={{.ImageName}},container_name={{.Name}}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
