services:
  vidt-video:
    image: harbor.rwiv.xyz/private/vidt:0.8.7
    container_name: vidt-video
    working_dir: /app
    entrypoint: .venv/bin/python3 -m vidt batch
    environment:
      PY_ENV: prod
      BATCH_COMMAND: video

      VIDEO_DOWNLOAD_CONFIG_PATH: /mnt/app/video_conf.yaml

      UNTF_ENDPOINT: "${UNTF_ENDPOINT}"
      UNTF_API_KEY: "${UNTF_API_KEY}"
      UNTF_TOPIC: "${UNTF_TOPIC}"
    volumes:
      - "${VIDEO_OUT_DIR_PATH}:/mnt/volume/out"
#      - "${VIDEO_TMP_DIR_PATH}:/mnt/volume/tmp"
      - "${VIDEO_DOWNLOAD_CONFIG_PATH}:/mnt/app/video_conf.yaml"
    labels:
      app: vidt
      host: ${HOSTNAME}
    logging:
      driver: json-file
      options:
        labels: app,host
        tag: "container_image={{.ImageName}},container_name={{.Name}}"
