services:
  vtask-loss:
    image: harbor.rwiv.xyz/private/vtask:0.6.5
    container_name: vtask-loss
    working_dir: /app
    entrypoint: python -m vtask batch
    environment:
      PY_ENV: prod
      BATCH_COMMAND: loss

      LOSS_CONFIG_PATH: /mnt/app/loss_conf.yaml

      UNTF_ENDPOINT: "${UNTF_ENDPOINT}"
      UNTF_API_KEY: "${UNTF_API_KEY}"
      UNTF_TOPIC: "${UNTF_TOPIC}"
    volumes:
      - "${LOSS_BASE_DIR_PATH}:/mnt/volume/app"
#      - "${LOSS_TMP_DIR_PATH}:/mnt/volume/tmp"
      - "${LOSS_CONFIG_PATH}:/mnt/app/loss_conf.yaml"
    labels:
      app: vtask
      host: ${HOSTNAME}
    logging:
      driver: json-file
      options:
        labels: app,host
        tag: "container_image={{.ImageName}},container_name={{.Name}}"
