metadata:
  name: vodify-redis
  namespace: media
vault:
  mount: kube
  path: media/vodify/redis
  version: 1
  secretName: vodify-redis
  refreshAfter: 30s

redis:
  global:
    storageClass: rook-ceph-block
  auth:
    existingSecret: vodify-redis
    existingSecretPasswordKey: password
  master:
    count: 1
    service:
      type: NodePort
      nodePorts:
        redis: 30285
  replica:
    replicaCount: 0
