apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.name }}-server
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.global.name }}-server
  template:
    metadata:
      labels:
        app: {{ .Values.global.name }}-server
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Values.global.name }}-server
          workingDir: "/app"
          command: ["python", "-m", "vtask", "server"]
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.server.service.targetPort }}
          env:
            - name: PY_ENV
              value: prod
            - name: SERVER_PORT
              value: "{{ .Values.server.service.targetPort }}"
            - name: REDIS_HOST
              value: {{ .Values.redis.host }}
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.secretName }}
                  key: {{ .Values.redis.passwordKey }}
            - name: SQS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.sqs.secretName }}
                  key: {{ .Values.secrets.sqs.accessKeyKey }}
            - name: SQS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.sqs.secretName }}
                  key: {{ .Values.secrets.sqs.secretKeyKey }}
            - name: SQS_REGION_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.stdlQueue.secretName }}
                  key: {{ .Values.secrets.stdlQueue.regionNameKey }}
            - name: SQS_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.stdlQueue.secretName }}
                  key: {{ .Values.secrets.stdlQueue.queueUrlKey }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
